[project]
name = "candy_bucket"
version = "0.0.12"
authors = [
  { name="Hipsterbrown", email="headhipster@hipsterbrown.com" },
]
description = "A Viam modular service to package a python program"
readme = "README.md"

[project.urls]
"Homepage" = "https://github.com/hipsterbrown/viam-candy-bucket"
