# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncode.proto\x12\x1dhipsterbrown.services.code.v1\x1a\x1cgoogle/api/annotations.proto\"5\n\x0b\x45\x63hoRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n\x04text\x18\x02 \x01(\tR\x04text\"\"\n\x0c\x45\x63hoResponse\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text2\xa6\x01\n\x0b\x43odeService\x12\x96\x01\n\x04\x45\x63ho\x12*.hipsterbrown.services.code.v1.EchoRequest\x1a+.hipsterbrown.services.code.v1.EchoResponse\"5\x82\xd3\xe4\x93\x02/\"-/hipsterbrown/api/v1/service/code/{name}/echob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'code_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CODESERVICE.methods_by_name['Echo']._options = None
  _CODESERVICE.methods_by_name['Echo']._serialized_options = b'\202\323\344\223\002/\"-/hipsterbrown/api/v1/service/code/{name}/echo'
  _ECHOREQUEST._serialized_start=75
  _ECHOREQUEST._serialized_end=128
  _ECHORESPONSE._serialized_start=130
  _ECHORESPONSE._serialized_end=164
  _CODESERVICE._serialized_start=167
  _CODESERVICE._serialized_end=333
# @@protoc_insertion_point(module_scope)
